#' Leipzig corpora demo
#'
#' A random subset of 250 sentences from all unannotated Indonesian Leipzig Corpora files.
"demo_corpus_leipzig"

#' Balinese newspapers texts
#'
#' A random ten corpus files of Balinese newspapers texts. These corpus files are raw plain texts without any annotation and which have not been split by sentences.
#"demo_corpus_bali"

#' Indonesian short stories
#'
#' A random ten corpus files of Indonesian short stories retrieved from online blog. These corpus files are raw plain texts without any annotation and which have not been split by sentences.
#"demo_corpus_id"

#' Filepath of the Indonesian Leipzig Corpora
#'
#' Package author's filepath to the plain-texts Indonesian Leipzig Corpora
"leipzig_corpus_path"

#' Filepath of the cleaned Indonesian Leipzig Corpora
#'
#' Package author's filepath to the cleaned version of the Indonesian Leipzig Corpora. The cleaned version means that the non-word tokens in the corpus (e.g. punctuation) have been separated by white-space.
#"leipzig_cleaned_path"

#' Filepath of the frequency list of the Indonesian Leipzig Corpora
#'
#' Package author's filepath to the frequency list files of the Indonesian Leipzig Corpora. These files are generated by the author using \emph{MonARCH High Performance Computing Cluster} at Monash University, Australia.
#"leipzig_mywordlist_path"

#' Filepath of the corpus-word vector the Indonesian Leipzig Corpora
#'
#' Package author's filepath to the corpus-word vector data of the Indonesian Leipzig Corpora. These files are the tokenised versions of the Indonesian Leipzig Corpora and are generated by the author using \emph{MonARCH High Performance Computing Cluster} at Monash University, Australia.
#"leipzig_vector_path"

#' Filepath of the Balinese newspapers corpus
#'
#' Package author's filepath to the Balinese newspapers texts.
#"orti_bali_path"

#' Indonesian stopwords
#'
#' Character vector containing Indonesian words selected as stopwords.
"stopwords"

